# Generated by Django 3.2.9 on 2021-12-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(verbose_name='课程')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('course_type', models.CharField(choices=[('F', '免费课'), ('P', '付费课')], default='F', max_length=1, verbose_name='付费类型')),
            ],
            options={
                'verbose_name': '查询记录',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(editable=False, max_length=20, verbose_name='订单ID')),
                ('product_line', models.CharField(max_length=20, verbose_name='产品线')),
                ('create_time', models.DateTimeField(verbose_name='下单时间')),
                ('user_id', models.CharField(max_length=40, verbose_name='用户ID')),
                ('user_mobile', models.CharField(max_length=20, verbose_name='手机号')),
                ('user_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('abtest', models.IntegerField(blank=True, null=True, verbose_name='ABTest')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('pay_channel', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('PE', '未支付'), ('SU', '支付成功'), ('CA', '取消'), ('OV', '过期'), ('RE', '退款')], default='PE', max_length=2, verbose_name='订单状态')),
                ('transaction_serial_number', models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='交易流水号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('fee_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='手续费')),
                ('refund_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='退款金额')),
                ('out_vendor', models.CharField(blank=True, max_length=100, null=True, verbose_name='渠道')),
                ('platform', models.CharField(blank=True, max_length=50, null=True, verbose_name='下单来源')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '订单',
            },
        ),
    ]
