# Generated by Django 3.2.9 on 2021-12-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单'},
        ),
    ]
