# Generated by Django 3.2.9 on 2021-12-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211206_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='查询条件')),
                ('objs', models.ManyToManyField(blank=True, to='dashboard.Order')),
            ],
            options={
                'verbose_name': '查询记录',
            },
        ),
    ]
